DROP DATABASE IF EXISTS srmdb;
CREATE DATABASE IF NOT EXISTS srmdb;
USE srmdb;

CREATE TABLE Users (
    UID INT(16) AUTO_INCREMENT,
    Username VARCHAR(64) NOT NULL,
    Name VARCHAR(64) NOT NULL,
    Password VARCHAR(64) NOT NULL,
    Administrator BOOLEAN NOT NULL DEFAULT 0,
    CONSTRAINT pk_UID PRIMARY KEY(UID)
);

CREATE TABLE Uploads (
    FID INT(16) AUTO_INCREMENT,
    UID INT(16) NOT NULL,
    Component VARCHAR(64) NOT NULL,
    Filename VARCHAR(64) NOT NULL,
    Fileext VARCHAR(64) NOT NULL,
    File LONGBLOB,
    CONSTRAINT pk_FID PRIMARY KEY(FID),
    CONSTRAINT fk_UID FOREIGN KEY(UID) REFERENCES Users(UID)
);